disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - multiline_arguments
  - multiline_parameters
identifier_name:
  excluded:
    - id
function_body_length: 50
file_length: 500
included:
  - Source
  - ../Source
