disabled_rules:
  - trailing_whitespace
  - void_return
opt_in_rules:
  - multiline_arguments
  - multiline_parameters
identifier_name:
  excluded:
    - id
line_length: 140
included:
  - Source
  - ../Source
