platform :ios, '8.0'

def myPods
    use_frameworks!
    if ENV['TRAVIS']
        pod 'Leash/RxSwift', :path => '../'
    else
        pod 'Leash/RxSwift'
    end
end

target 'Example' do
    myPods
end

target 'Tests' do
    myPods
    pod 'OHHTTPStubs/Swift', '~> 6.0'
end
