language: swift
osx_image: xcode11
podfile: Example/Podfile

before_install:
  - gem install cocoapods
  - pod repo update

script:
  - xcodebuild -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator -destination 'name=iPhone 11' -enableCodeCoverage YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J Leash
